################################################################################
################################################################################
###
###  This file is automatically generated. Do not change this file! Changes
###  will get overwritten! Change the source file for "setup.py" instead.
###  This is either 'packageinfo.json' or 'packageinfo.jsonc'
###
################################################################################
################################################################################


from setuptools import setup

def readme():
	with open("README.md", "r", encoding="UTF-8-sig") as f:
		return f.read()

setup(
	author = "Jürgen Knauth",
	author_email = "pubsrc@binary-overflow.de",
	classifiers = [
		"Development Status :: 4 - Beta",
		"License :: OSI Approved :: Apache Software License",
	],
	description = "This python module provides a high level interface to provide a clean API for executing commands and reading and writing files transparently: It doesn't matter if you operate locally or remotely or as a regular user or as root via sudo.",
	download_url = "https://github.com/jkpubsrc/python-module-jk-invoke/tarball/0.2020.4.6",
	include_package_data = False,
	install_requires = [
		"jk_pwdinput",
	],
	keywords = [
		"ssh",
	],
	license = "Apache 2.0",
	name = "jk_invoke",
	packages = [
		"jk_invoke",
	],
	url = "https://github.com/jkpubsrc/python-module-jk-invoke",
	version = "0.2020.4.6",
	zip_safe = False,
	long_description = readme(),
	long_description_content_type="text/markdown",
)
